#define UPARROWROWOFFSET    2
#define DNARROWROWOFFSET    2
#define SCROLLBARCOLOFFSET  3

#define ON_TITLE                0
#define SCROLLBAR_UPARROW       100
#define SCROLLBAR_DNARROW       101
#define SCROLLBAR_ABOVE_SLIDER  102
#define SCROLLBAR_BELOW_SLIDER  103
#define SCROLLBAR_ON_SLIDER     104
#define BUTTONS                 105
#define DISPLAY_AREA            106
#define OUTSIDE_DIALOG          107

#define INIT_DIALOG  200
