/*****************************************************************************/
/* File:                                             IBM INTERNAL USE ONLY   */
/*   msgdef.h                                                                */
/*                                                                           */
/* Description:                                                              */
/*   SD86 messages definitions.                                              */
/*                                                                           */
/* History:                                                                  */
/*   11/29/88 Created.                                                       */
/*                                                                           */
/*****************************************************************************/

#define OK                   0
#define EXEOPEN              1
#define EXEINITERROR         3
#define BADEXE               4
#define BADDEBHDR            5
#define OUTOFHEAP            6
#define EXCBEFPROC           7
#define ENTRYPTERR           9
#define TOOMANYDLLS          11
#define BADSYMBOLICINFO      12
#define NOCODESEGS           13
#define DLLINITERROR         14
#define MEMALLOC             15
#define BADINVOCATIONOPTION  16
#define MOUSEERROR           17
