/* For those times when you wish it weren't so */

#define OOquit		(-1)
#define OOstop		1

#define OOvrows 	10

#define OOgo		100
#define OOptrace	101
#define OOpterror	102
#define OOmaxexecs	103
#define OOpthuh 	104
#define OOentry 	105
#define OObrkrdin	106
#define OObrkwrin	107
#define OObrkrdout	108
#define OObrkwrout	109
#define OObrkrem	110
#define OObrkund	111
#define OOilen		112
#define OOsvc		113
#define OOmodname	114
#define OOdisasm	115
#define OOqdatar	116
#define OOdropdr	117
#define OOstub2code	118
#define OOstack 	119

#define OOstub		120
#define OOstub1 	121
#define OOstub2 	122
#define OOmodbase	123

#define OOfault1	130
#define OOfault2	131
#define OOfault3	132
#define OOfault4	133
#define OOfault5	134
#define OOexcept	136
#define OOframe 	137
#define OOmaxtrd	138
#define OOduptrd	139
#define OOnewtrd	140
#define OOacttrd	141
#define OOtrap		142
#define OOexception	143
#define OOexit1 	144
#define OOinit1 	145
#define OOthaw		146
#define OOinit2 	147
#define OOdeltrd	148
#define OOexit2 	149
#define OOkiltrd	150
#define OOexit3 	151

#define OOterm1 	190
#define OOterm2 	191

#define OOvioclr	200
#define OOvioshow	201
#define OOfreefp	202
