/*****************************************************************************/
/* - defines for some likely tcpip errors.                                   */
/*****************************************************************************/
#define CANT_LOAD_TCPIP_DLL    1
#define TCPIP_NOT_RUNNING      2
#define TCPIP_ERROR            3
#define TCPIP_NO_SERVICES_PORT 4
#define TCPIP_NO_HOST_NAME     5
#define TCPIP_ESP_NOT_STARTED  6

#define MAX_IP_NAME 256
