/*****************************************************************************/
/* File:                                             IBM INTERNAL USE ONLY   */
/*   xcpt.h                                                                  */
/*                                                                           */
/* Description:                                                              */
/*   exception stuff.                                                        */
/*                                                                           */
/*****************************************************************************/

#define MAXEXCEPTIONS  27

#define NO_NOTIFY       0
#define NOTIFY          1

#define XCPT_PROGRAM    0

